# Generated by Django 5.0.10 on 2024-12-09 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_body'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('wagtailvideos', '0015_video_height_video_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='contact_cta',
            field=models.CharField(blank=True, help_text='Contact forms CTA', max_length=255, verbose_name='Contact CTA'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_cta_link',
            field=models.ForeignKey(blank=True, help_text='contact Page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Contact CTA link'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='header_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailvideos.video'),
        ),
    ]
